apiVersion: v2
appVersion: "1.0"
description: A Helm chart for a Kubernetes app
name: hello
version: 1.0

dependencies:
  - name: mongodb
    version: 9.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: rabbitmq
    version: 7.7.1
    repository: https://charts.bitnami.com/bitnami
